# TCP listener for ESP32 / Flutter / backend
listener 1883
protocol mqtt

# WebSocket listener for browser debug panel
listener 9001
protocol websockets

allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl
